"""is admin not nullable

Revision ID: d1e38467a265
Revises: 255ec38547fd
Create Date: 2024-07-02 21:38:25.863063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fast_zero.models import table_registry

# revision identifiers, used by Alembic.
revision: str = 'd1e38467a265'
down_revision: Union[str, None] = '255ec38547fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute(table_registry.metadata.tables['users'].update().where(table_registry.metadata.tables['users'].c.is_admin == None).values({'is_admin':False}))

    op.alter_column('users', 'is_admin',nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('users', 'is_admin',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=True)
    # ### end Alembic commands ###
    ...